lr=2e-6
tau=0.3
sp=2
ckptname=mistral-dft-lr${lr}-tau${tau}-u_init0-s${sp}-e2-gamma0.9
ACCELERATE_LOG_LEVEL=info accelerate launch --main_process_port 29507 --config_file recipes/accelerate_configs/deepspeed_zero3.yaml scripts/run_dft.py recipes/dft/mistral_base.yaml \
    --learning_rate=${lr} \
    --tau=${tau} \
    --u_init=0 \
    --output_dir=./ckpts/${ckptname} \
    --run_name=${ckptname} \
    --samples_per_prompt=${sp} \
    --gamma=0.90 \
    --ref_free=true